apiVersion: v1
kind: Service
metadata:
  labels:
    apps: oldboyedu-svc
    class: linux85
  name: oldboyedu-linux85-web
  namespace: default
spec:
  selector:
    hobby: k8s
    auther: jasonyin
  type: ClusterIP
  ports:
    - port: 88
      targetPort: 80
      protocol: TCP


