apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-test
spec:
  replicas: 3
  selector:
    school: oldboyedu
    apps: web
  template:
    metadata:
      name: web
      labels:
        school: oldboyedu
        apps: web
        version: v0.1
    spec: 
      containers:
        - name: nginx
          image: nginx:1.23.4-alpine
