apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      school: oldboyedu
  template:
    metadata:
      labels:
        school: oldboyedu
        version: v1
    spec:
      volumes:
        - name: index
          hostPath:
            path: /tmp/index.html
            type: FileOrCreate
      containers:
        - name: nginx
          image: nginx:1.23.4-alpine
          volumeMounts:
            - name: index
              mountPath: /usr/share/nginx/html/index.html
              

---
apiVersion: v1
kind: Service
metadata:
  name: svc-rs-demo
spec:
  selector:
    school: oldboyedu
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
