apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      school: oldboyedu
  template:
    metadata:
      labels:
        school: oldboyedu
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.4-alpine

---
apiVersion: v1
kind: Service
metadata:
  name: svc-rs-demo
spec:
  selector:
    school: oldboyedu
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
