apiVersion: v1
kind: Pod
metadata:
  name: linux85-imagepullsecret-002
spec:
  nodeName: k8s192.oldboyedu.com
  # 指定拉取镜像的secret验证信息
  imagePullSecrets:
  - name: linux85
  containers:
  - name: linux
    image: harbor.oldboyedu.com/linux85/jasonyin2020/oldboyedu-linux-tools:v0.1
    stdin: true
