apiVersion: v1
kind: Pod
metadata:
  name: linux85-volume-emptydir-001
spec:
  volumes:
    - name: data01
      emptyDir: {}
  containers:
    - name: web
      image: harbor.oldboyedu.com/web/nginx:1.23.4-alpine
      volumeMounts:
        - name: data01
          mountPath: /usr/share/nginx/html
    - name: linux
      image: harbor.oldboyedu.com/linux/alpine:latest
      stdin: true
      volumeMounts:
        - name: data01
          mountPath: /oldboyedu-data
