apiVersion: v1
kind: Pod
metadata:
  name: linux85-volume-hostpath-001
spec:
  nodeName: k8s192.oldboyedu.com
  volumes:
    - name: data01
      emptyDir: {}
    - name: data02
      hostPath:
        path: /oldboyedu-data
  containers:
    - name: web
      image: harbor.oldboyedu.com/web/nginx:1.23.4-alpine
      volumeMounts:
        - name: data02
          mountPath: /usr/share/nginx/html

---
apiVersion: v1
kind: Pod
metadata:
  name: linux85-volume-hostpath-002
spec:
  nodeName: k8s192.oldboyedu.com
  volumes:
    - name: linux85-data 
      hostPath:
        path: /oldboyedu-data
  containers:
    - name: linux
      image: harbor.oldboyedu.com/linux/alpine:latest
      stdin: true
      volumeMounts:
        - name: linux85-data
          mountPath: /oldboyedu-data-linux85
