apiVersion: v1
kind: Pod
metadata: 
  name: linux85-stress-003
spec:
  nodeName: k8s193.oldboyedu.com
  containers:
    - name: stress
      image: harbor.oldboyedu.com/tools/jasonyin2020/oldboyedu-linux-tools:v0.1
      args:
        - "sleep"
        - "5000"
      resources:
        requests:
          #memory: 10G
          memory: 256M
          cpu: 250m
        limits:
          memory: 500M
          cpu: 500m
