apiVersion: v1
kind: ReplicationController
metadata:
  name: oldboyedu-linux85-web-rc
  labels:
    school: oldboyedu
    class: linux85
    apps: rc
  namespace: default
spec:
  replicas: 5
  selector:
    classroom: jiaoshi05
    address: oldboyedu-shahe
  template:
    metadata:
      labels:
        classroom: jiaoshi05
        address: oldboyedu-shahe
        hobby: k8s
        auther: jasonyin
    spec:
      containers:
        - name: nginx
          image: harbor.oldboyedu.com/web/nginx:1.23.4-alpine

