apiVersion: v1
kind: ReplicationController
metadata:
  name: oldboyedu-linux85-web-rc-probe
  labels:
    school: oldboyedu
    class: linux85
    apps: rc
  namespace: default
spec:
  replicas: 3
  selector:
     classroom: jiaoshi05
     address: oldboyedu-shahe
  template:
    metadata:
      labels:
        classroom: jiaoshi05
        address: oldboyedu-shahe
        hobby: k8s
        auther: jasonyin
    spec:
      containers:
      - name: linux85-exec
        image: harbor.oldboyedu.com/web/nginx:1.23.4-alpine
        # 判断服务是否健康，若检查不通过，将Pod直接重启。
        livenessProbe:
          httpGet:
            port: 80
            path: /huozhe.html
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        # 判断服务是否就绪，若检查不通过，将Pod标记为未就绪状态。
        readinessProbe:
          httpGet:
            port: 80
            path: /oldboyedu.html
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        # 启动时做检查，若检查不通过，直接杀死容器。
        # startupProbe探针通过后才回去执行readinessProbe和livenessProbe哟~
        startupProbe:
          httpGet:
            port: 80
            path: /start.html
          failureThreshold: 3
          initialDelaySeconds: 35
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1

---

apiVersion: v1
kind: Service
metadata:
  name: oldboyedu-linux85-web-readinessprobe-httpget
  namespace: default
  labels:
    apps: oldboyedu-svc
    class: linux85
spec:
  selector:
    hobby: k8s
    auther: jasonyin
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  clusterIP: 10.200.100.220
