apiVersion: v1
kind: Pod
metadata:
  name: linux85-game-cm-env
spec:
  nodeName: k8s192.oldboyedu.com
  containers:
    - name: game
      image: harbor.oldboyedu.com/oldboyedu-games/jasonyin2020/oldboyedu-games:v0.1
      env:
        - name: OLDBOYEDU_LINUX85_SCHOOL
          valueFrom:
            configMapKeyRef:
              name: linux85-config
              key: school
        - name: OLDBOYEDU_LINUX85_CLASS
          valueFrom:
            configMapKeyRef:
              name: linux85-config
              key: class
        - name: OLDBOYEDU_LINUX85_MYCFG
          valueFrom:
            configMapKeyRef:
              name: linux85-config
              key: my.cfg
        - name: OLDBOYEDU_LINUX85_STUDENTINFO
          valueFrom:
            configMapKeyRef:
              name: linux85-config
              key: student.info
