apiVersion: v1
kind: Pod
metadata:
  name: linux85-volume-cm-008
spec:
  nodeName: k8s192.oldboyedu.com
  volumes:
    - name: data
      configMap:
        name: linux85-config
        items:
          - key: student.info
            path: oldboyedu-linux85-student.info
  containers:
    - name: web
      image: harbor.oldboyedu.com/web/nginx:1.23.4-alpine
      command: ["tail","-f","/etc/hosts"]
      volumeMounts:
        - name: data
          mountPath: /etc/nginx/nginx.conf
          subPath: oldboyedu-linux85-student.info
