apiVersion: v1
kind: Pod
metadata:
  name: linux85-games-ketanglianxi-002
spec:
  # hostNetwork: true
  nodeName: k8s192.oldboyedu.com
  volumes:
  - name: data
    configMap:
      name: oldboyedu-linux85-games
      items:
      - key: nginx.conf
        path: nginx.conf
  containers:
  - name: game
    image: harbor.oldboyedu.com/oldboyedu-games/jasonyin2020/oldboyedu-games:v0.1
    volumeMounts:
    - name: data
      mountPath: /usr/local/nginx/conf/nginx.conf
      subPath: nginx.conf
    # 指定容器的端口映射相关字段
    ports:
      # 指定容器的端口号
    - containerPort: 80
      # 绑定主机的IP地址
      hostIP: "0.0.0.0"
      # 指定绑定的端口号
      hostPort: 88
      # 给该端口起一个别名，要求唯一
      name: game
      # 指定容器的协议
      protocol: TCP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: oldboyedu-linux85-games
data:
  nginx.conf: |
      worker_processes  1;
      events {
          worker_connections  1024;
      }
      http {
          include       mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          keepalive_timeout  65;
          server {
              listen       80;
              root        /usr/local/nginx/html/bird/;
              server_name   game01.oldboyedu.com;
          }
          server {
              listen       80;
              root        /usr/local/nginx/html/pinshu/;
              server_name   game03.oldboyedu.com;
          }
          server {
              listen       80;
              root        /usr/local/nginx/html/tanke/;
              server_name   game05.oldboyedu.com;
          }
          server {
              listen       80;
              root        /usr/local/nginx/html/pingtai/;
              server_name   game02.oldboyedu.com;
          }
          server {
              listen       80;
              root        /usr/local/nginx/html/chengbao/;
              server_name   game04.oldboyedu.com;
          }
      }
